Vagrant::Config.run do |config|
  config.vm.box = "collectorsquest"
  config.vm.box_url = "http://collectorsquest.s3.amazonaws.com/virtualbox/collectorsquest.2012-07-24.box"

  config.vm.network :hostonly, "172.16.183.128"
  config.vm.forward_port(80, 9458)
  config.vm.forward_port(443, 9459)
  config.vm.share_folder("vhosts", "/mnt/vhosts", "../../../vhosts", :nfs => true)
  config.vm.share_folder("tmp", "/mnt/tmp", "/tmp", :nfs => true)

  # If you want to specify the host OS, create a file 'platform'
  # in the same directory as the .vagrant file.
  platform = (File.exists? 'platform') ? File.read('platform').strip : :detect

  if platform == 'windows'
    config.vm.share_folder("vhosts", "/mnt/vhosts", "../../../vhosts", :nfs => false, :owner => "apache", :group => "apache")
    config.vm.share_folder("tmp", "/mnt/tmp", ENV['TEMP'], :nfs => false)
  elsif platform == 'darwin'
    config.vm.share_folder("tmp", "/mnt/tmp", "/Volumes/Storage/tmp", :nfs => true)
  end

  config.vm.customize ["modifyvm", :id, "--name", "Collectors Quest", "--memory", "1024", "--cpus", "1"]

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../cookbooks"

    chef.add_recipe("main")
    chef.add_recipe("main::github")
    chef.add_recipe("main::web")
    chef.add_recipe("sphinx")
    chef.add_recipe("development")
  end

  config.package.name = "collectorsquest"
  # config.vm.boot_mode = :gui
end
